name: Deploy React to S3

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Project
        run: npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://aws-cicd-test-pipeline-2025 --delete --region us-east-1

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Notify via SNS Email
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:471112947524:NewGitCommit \
            --subject "New Version of React App Deployed" \
            --message "Latest commit has been successfully deployed to S3 and CloudFront cache was invalidated, test if Application is running properly!"
